name: Fetch ICON-D2 GRIB2 and Generate PNGs

on:
  schedule:
    - cron: '30 0 * * *'
    - cron: '30 4 * * *'
    - cron: '30 7 * * *'
    - cron: '30 10 * * *'
    - cron: '30 13 * * *'
    - cron: '30 16 * * *'
    - cron: '30 19 * * *'
    - cron: '30 22 * * *'
  workflow_dispatch:

jobs:
  fetch_and_generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set RUN and DATE
        run: |
          HOUR=$(date -u +%H)
          case $HOUR in
            01|02|03) RUN=00 ;;
            04|05|06) RUN=03 ;;
            07|08|09) RUN=06 ;;
            10|11|12) RUN=09 ;;
            13|14|15) RUN=12 ;;
            16|17|18) RUN=15 ;;
            19|20|21) RUN=18 ;;
            22|23|00) RUN=21 ;;
          esac
          echo "RUN=$RUN" >> $GITHUB_ENV
          DATE=$(date -u +%Y%m%d)
          echo "DATE=$DATE" >> $GITHUB_ENV

      - name: Download t2m GRIB2 files
        run: |
          mkdir -p data/t2m
          cd data/t2m
          for i in $(seq 0 47); do
            i_padded=$(printf "%03d" $i)
            URL="https://opendata.dwd.de/weather/nwp/icon-d2/grib/${{ env.RUN }}/t_2m/icon-d2_germany_regular-lat-lon_single-level_${{ env.DATE }}${{ env.RUN }}_${i_padded}_2d_t_2m.grib2.bz2"
            wget -O t2m_${i_padded}.grib2.bz2 "$URL" || echo "Datei $URL nicht verfügbar, überspringe..."
            if [ -f "t2m_${i_padded}.grib2.bz2" ]; then
              bunzip2 -f t2m_${i_padded}.grib2.bz2
            fi
          done

      - name: Download ww GRIB2 files
        run: |
          mkdir -p data/ww
          cd data/ww
          for i in $(seq 0 47); do
            i_padded=$(printf "%03d" $i)
            URL="https://opendata.dwd.de/weather/nwp/icon-d2/grib/${{ env.RUN }}/ww/icon-d2_germany_regular-lat-lon_single-level_${{ env.DATE }}${{ env.RUN }}_${i_padded}_2d_ww.grib2.bz2"
            wget -O ww_${i_padded}.grib2.bz2 "$URL" || echo "Datei $URL nicht verfügbar, überspringe..."
            if [ -f "ww_${i_padded}.grib2.bz2" ]; then
              bunzip2 -f ww_${i_padded}.grib2.bz2
            fi
          done

      - name: Download tp GRIB2 files
        run: |
          mkdir -p data/tp
          cd data/tp
          for i in $(seq 1 48); do
            i_padded=$(printf "%03d" $i)
            URL="https://opendata.dwd.de/weather/nwp/icon-d2/grib/${{ env.RUN }}/tp/icon-d2_germany_regular-lat-lon_single-level_${{ env.DATE }}${{ env.RUN }}_${i_padded}_2d_tp.grib2.bz2"
            wget -O tp_${i_padded}.grib2.bz2 "$URL" || echo "Datei $URL nicht verfügbar, überspringe..."
            if [ -f "tp_${i_padded}.grib2.bz2" ]; then
              bunzip2 -f tp_${i_padded}.grib2.bz2
            fi
          done

      - name: Remove old PNGs of current RUN from repo
        run: |
          git rm -r --ignore-unmatch pngs/${{ env.RUN }} || true

      - name: Generate PNGs
        run: |
          python scripts/generate_pngs.py data/t2m pngs/${{ env.RUN }}/t2m t2m
          python scripts/generate_pngs.py data/ww pngs/${{ env.RUN }}/ww ww
          python scripts/generate_pngs.py data/tp pngs/${{ env.RUN }}/tp tp

      - name: Commit PNGs
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add pngs/${{ env.RUN }}/t2m/* || true
          git add pngs/${{ env.RUN }}/ww/* || true
          git add pngs/${{ env.RUN }}/tp/* || true

          git commit -m "Update ICON-D2 run ${{ env.RUN }} for ${{ env.DATE }}" || echo "Keine Änderungen zum Commit"
          git push
